### PR TITLE
Add multibyte-safe strlen() and substr()

### PR DESCRIPTION
**Pull request by sarciszewski**
This defines a trait called \RandomLib\Util which imports the methods to be used in other classes.

### CODE REVIEW

**Comment by sarciszewski** [comment]
Okay, done revising the PR. I totally spaced and forgot traits weren't in 5.3

**Comment by ircmaxell** [comment]
This should be put on [SecurityLib](https://github.com/ircmaxell/SecurityLib) instead, as it's a generic utility function unrelated to randomness. And since RandomLib depends on SecurityLib already, shouldn't be any issues there.

**Comment by sarciszewski** [comment]
Oh. Ok :)

**Comment by ircmaxell** [comment]
Well, you'll still need the usages here, so there'll still need to be a PR against this lib.

**Comment by sarciszewski** [comment]
Yeah, I'll open a new one that links to the SecurityLib ones.

**Pull request closed without merging**
